source 'https://rubygems.org'
ruby "1.9.3"

gem 'thin'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-assetpack'
gem 'sinatra-ember'
gem 'sass'
gem 'json'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-sqlite-adapter'
gem 'logger'
gem 'active_support'
